luchta-io/forma4j

- .github/workflows/gradle.yml
- .github/workflows/publish.yml
- build.gradle
バージョン情報の変更
ビルド時にエラーが発生した場合stacktraceを出力する
> バージョン情報の変更

- build.gradle
> バージョンを0.1.1-SNAPSHOTに変更

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> バージョンを0.1.1に変更

- .github/dependabot.yml
gradleを対象にdependabot用のymlファイルを作成
> dependabot用のymlファイルを新規作成

- build.gradle
jaxb-impl 3.0.2 -> 4.0.0
jackson-core 2.13.2 -> 2.13.3
jackson-datatype-jsr310 2.13.2 -> 2.13.3
> 依存ライブラリのバージョン変更

- .github/workflows/gradle.yml
- .github/workflows/publish.yml
- build.gradle
> java11 -> java17

- src/main/java/io/luchta/forma4j/context/databind/json/JsonNode.java
- src/main/java/io/luchta/forma4j/writer/Context.java
- src/main/java/io/luchta/forma4j/writer/Writer.java
- src/main/java/io/luchta/forma4j/writer/definition/XmlDocument.java
- src/main/java/io/luchta/forma4j/writer/definition/schema/ElementType.java
- src/main/java/io/luchta/forma4j/writer/definition/schema/element/ListElement.java
- src/main/java/io/luchta/forma4j/writer/definition/schema/element/Root.java
- src/main/java/io/luchta/forma4j/writer/definition/schema/element/Sheet.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/horizontalfor/HorizontalForHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/list/ListHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/row/RowHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/sheet/SheetHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/verticalfor/VerticalForHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/address/XlsxColumnNumber.java
- src/main/java/io/luchta/forma4j/writer/engine/resolver/VariableResolver.java
- src/test/java/io/luchta/forma4j/writer/WriterTest.java
- src/test/resources/writer/test.xml
> 設定ファイルなしの書き込み処理

- build.gradle
バージョンを 1.0.0-SNAPSHOT から 1.0.0 に変更
> version 1.0.0-SNAPSHOT -> 1.0.0

- .github/workflows/gradle.yml
- gradle/wrapper/gradle-wrapper.properties
> java-varsion 18 を追加

- build.gradle
バージョン変更
1.1.0-SNAPSHOT -> 1.1.0
> 1.1.0-SNAPSHOT -> 1.1.0

- src/main/java/io/luchta/forma4j/reader/excel/ExcelReader.java
- src/main/java/io/luchta/forma4j/reader/model/tag/FormaReaderTag.java
- src/main/java/io/luchta/forma4j/reader/model/tag/SheetTag.java
- src/test/java/io/luchta/forma4j/reader/FormaReaderTest.java
読み込みの設定ファイルに複数シート設定されたときの JSON の構造を変更
> 複数シート設定時の JSON の構造の変更

- README.md
- build.gradle
> バージョン情報の修正

- build.gradle
> version 1.2.0 -> 1.2.1

- README.md
- build.gradle
> Merge master to v1.3.0

- .github/dependabot.yml
dependabotのインターバルをweeklyからmonthlyに変更
> dependabotのインターバルをweeklyからmonthlyに変更

- build.gradle
> version 1.2.1 -> 1.2.2

- src/main/java/io/luchta/forma4j/writer/processor/poi/WorkbookBuilder.java
- src/test/java/io/luchta/forma4j/writer/WriterTest.java
テンプレート使用時にテンプレート上の空行に書き込もうとするとエラーとなる不具合を修正
> 行作成時の不具合を修正

- src/main/java/io/luchta/forma4j/writer/FormaWriter.java
- src/main/java/io/luchta/forma4j/writer/processor/XlsxPassword.java
- src/test/java/io/luchta/forma4j/writer/WriterTest.java
> パスワード付きExcelの書き込み対応

- src/main/java/io/luchta/forma4j/writer/processor/poi/setting/StyleSetting.java
- src/test/java/io/luchta/forma4j/writer/WriterTest.java
close #128 
* 値に `\n`, `\r\n` が入ってきた場合は、ファイルを開いた時点で折り返されて表示される
* 値に `\r` のみが入ってきた場合は変わらずissueに記載の通りの動作になる
> issue/128 セル中の改行がうまくいっていない件の対応

- build.gradle
hasProperty(System.hasProperty) が常にfalseを返すのでproject.hasPropertyに修正
> hasProperty -> project.hasProperty

- README.md
- build.gradle
> version1.3.2 -> 1.4.0

- src/main/java/io/luchta/forma4j/reader/excel/objectreader/CellReader.java
- src/test/java/io/luchta/forma4j/reader/FormaReaderTest.java
- src/test/resources/reader/simple_cell_read_test.xml
> nameにドットで区切れられた文字を指定されたとき階層構造化する

- src/main/java/io/luchta/forma4j/context/databind/convert/JsonSerializer.java
- src/main/java/io/luchta/forma4j/reader/excel/objectreader/CellReader.java
- src/main/java/io/luchta/forma4j/reader/excel/objectreader/ListReader.java
- src/main/java/io/luchta/forma4j/reader/model/tag/FormaReaderTag.java
- src/test/java/io/luchta/forma4j/reader/FormaReaderTest.java
- src/test/resources/reader/simple_cell_read_by_index_test.xml
- src/test/resources/reader/simple_cell_read_by_name_test.xml
> JSONキー名・空白セルの扱い変更

- src/main/java/io/luchta/forma4j/context/databind/convert/JsonSerializer.java
- src/main/java/io/luchta/forma4j/context/databind/json/JsonObject.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/BorderProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/FontSizeProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/NotSupportProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyle.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/resolver/StyleResolver.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/WorkbookBuilder.java
- src/test/java/io/luchta/forma4j/writer/FormaWriterTest.java
- src/test/resources/writer/style.xml
> Issue/168 文字サイズのスタイル指定に対応する

- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/FontStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
> Issue/169 文字の書体（太字, 斜体）のスタイル指定に対応する

- src/main/java/io/luchta/forma4j/context/databind/convert/JsonDeserializer.java
- src/test/java/io/luchta/forma4j/databind/convert/JsonDeserializerTest.java
> Issue/166 JsonDeserializer: 値がnullの場合にNPEが発生する

- README.md
- build.gradle
> バージョン情報を変更

- .github/workflows/gradle.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
setup-javaのバージョンを `3.4.0` から `4` に変更。
CIでテストするJavaのバージョンを `11`, `15`, `16`, `17`, `18` から `11`, `17`, `21` に変更。
> setup-javaのバージョンアップ

- src/main/java/io/luchta/forma4j/writer/processor/poi/WorkbookBuilder.java
https://github.com/luchta-io/forma4j/releases/tag/v1.4.4
> v1.4.4をマージ

- src/main/java/io/luchta/forma4j/writer/definition/schema/attribute/row/AutoFilter.java
- src/main/java/io/luchta/forma4j/writer/definition/schema/element/Row.java
- src/main/java/io/luchta/forma4j/writer/engine/buffer/accumulater/BuildAccumulator.java
- src/main/java/io/luchta/forma4j/writer/engine/buffer/accumulater/support/RowPropertyMap.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/element/RowHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/address/XlsxCellAddress.java
- src/main/java/io/luchta/forma4j/writer/engine/model/column/XlsxColumnRange.java
- src/main/java/io/luchta/forma4j/writer/engine/model/row/XlsxRow.java
- src/main/java/io/luchta/forma4j/writer/engine/model/row/address/XlsxRowAddress.java
- src/main/java/io/luchta/forma4j/writer/engine/model/row/property/AutoFilterProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/row/property/XlsxRowProperties.java
- src/main/java/io/luchta/forma4j/writer/engine/model/row/property/XlsxRowProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/WorkbookBuilder.java
> オートフィルター機能を追加

- build.gradle
Maven Repositoryに公開するときにfatjarを作成して公開するように変更。
> publish時にfatjarを作成する

- build.gradle
> Revert "Bump com.sun.xml.bind:jaxb-impl from 4.0.3 to 4.0.5"

- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/BackGroundColorProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
- src/test/resources/writer/一覧.xml
セルに背景色をセットできるようにする。
style="background-color: #FFC000"
> セルに背景色をセットできるようにする

- README.md
> ドキュメントへのリンクを追加

- src/main/java/io/luchta/forma4j/writer/engine/handler/element/ColumnHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/element/HorizontalForHandler.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/element/RowHandler.java
- src/test/java/io/luchta/forma4j/writer/horizontalFor/HorizontalForTest.java
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_jsonnodes.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_jsonnodes_3_5.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_jsonnodes_3_5_check.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_jsonnodes_check.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_list.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_list_3_5.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_list_3_5_check.xml
- src/test/resources/writer/horizontalFor/horizontal_for_cell_set_list_check.xml
- src/test/resources/writer/horizontalFor/horizontal_for_with_vertical_for.xml
- src/test/resources/writer/horizontalFor/horizontal_for_with_vertical_for_3_5.xml
- src/test/resources/writer/horizontalFor/horizontal_for_with_vertical_for_3_5_check.xml
- src/test/resources/writer/horizontalFor/horizontal_for_with_vertical_for_check.xml
- horizontal-forタグのテストを作成
- 行、列の位置がずれる不具合の修正
- horizontal-forタグにstartRowIndex、startColumnIndexを指定してもループが動作しない不具合を修正
> horizontal-forの動作修正

- build.gradle
forma4j-x.x.x-all.jar -> forma4j-x.x.x.jar
> classifierを削除

- src/main/java/io/luchta/forma4j/reader/compile/parse/tagbuilder/HForBuilder.java
- src/main/java/io/luchta/forma4j/reader/excel/objectreader/HForReader.java
- src/main/java/io/luchta/forma4j/reader/model/tag/HForTag.java
- src/test/java/io/luchta/forma4j/reader/FormaReaderTest.java
- src/test/java/io/luchta/forma4j/reader/hfor/HForTest.java
- src/test/resources/reader/hfor/hfor.xml
- src/test/resources/reader/hfor/hfor_beyond_last_column.xml
- src/test/resources/reader/hfor/hfor_from_1_to_3.xml
- src/test/resources/reader/hfor/hfor_row_3_from_1_to_3.xml
- src/test/resources/reader/hfor/hfor_row_7.xml
- 最終列以降のインデックスを指定された場合、無限ループになる不具合の修正
- rowを指定しても1行目を読み込む不具合の修正
> hforタグの不具合修正

- README.md
- build.gradle
- docs/gradle/gradle.md
> バージョン情報を修正

- build.gradle
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
> Apatch POI 5 -> 4

- docs/writer/style.md
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/FontFamilyProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
styleにfont-familyを追加し、フォントファミリーを設定できるように修正。
> フォントファミリーの設定

- README.md
- build.gradle
- docs/gradle/gradle.md
- docs/writer/style.md
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/ColorProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/FontFamilyProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/border/Border.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/border/BorderBottomProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/border/BorderLeftProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/border/BorderProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/border/BorderRightProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/border/BorderTopProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
> v1.6.0をdev-mへマージ

- README.md
- build.gradle
- docs/gradle/gradle.md
- src/main/java/io/luchta/forma4j/writer/engine/handler/element/RowHandler.java
> v1.6.1をマージ

- README.md
- build.gradle
- docs/gradle/gradle.md
> バージョン変更 1.6.1 -> 1.6.2

- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/align/HorizontalAlignProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/align/VerticalAlignProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
styleに `v-align` と `h-align` を追加して、垂直方向と水平方向の文字位置を設定できるように機能追加。
> 垂直水平方向の文字位置設定

- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/XlsxCellStyleProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/align/HorizontalAlignProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/align/VerticalAlignProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
> v1.7.0をマージ

- docs/writer/style.md
> styleのドキュメント修正

- src/main/java/io/luchta/forma4j/writer/definition/schema/ElementList.java
- src/main/java/io/luchta/forma4j/writer/engine/handler/element/SheetHandler.java
- src/test/java/io/luchta/forma4j/writer/sheet/SheetTest.java
- src/test/resources/writer/sheet/sheet_collection.xml
- src/test/resources/writer/sheet/sheet_collection_check.xml
sheetのcollectionを設定したとき子要素がlistでないとエラーとなる不具合を修正。
> sheetのcollection設定時の動作を修正

- build.gradle
publishする先を `mars-repository-hosting` へ変更。
> publish先を変更

- src/main/antlr/io/luchta/forma4j/antlr/style/Style.g4
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/BackGroundColorProperty.java
- src/main/java/io/luchta/forma4j/writer/engine/model/cell/style/ColorProperty.java
- src/main/java/io/luchta/forma4j/writer/processor/poi/CellStyleBuilder.java
- src/test/resources/writer/style.xml
`アルファベット` `数値` `-` ` ` のみの入力だったセルのスタイルに日本語を入力可能に変更。
> セルのスタイルに日本語名を設定できるように修正

- src/main/java/io/luchta/forma4j/reader/excel/objectreader/CellReader.java
- src/test/java/io/luchta/forma4j/reader/cell/CellTest.java
> v1.7.2をマージ

- src/main/java/io/luchta/forma4j/reader/FormaReader.java
- src/main/java/io/luchta/forma4j/reader/excel/objectreader/HForReader.java
- src/main/java/io/luchta/forma4j/reader/excel/objectreader/VForReader.java
- src/main/java/io/luchta/forma4j/reader/xml/XmlReader.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/Parser.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/CellBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/FormaReaderBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/HForBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/ListBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/SheetBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/TagBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/TagBuilderFactory.java
- src/main/java/io/luchta/forma4j/reader/xml/parse/tagbuilder/VForBuilder.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/RelationAnalysis.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/CellTagAnalyzer.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/HForTagAnalyzer.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/ListTagAnalyzer.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/SheetTagAnalyzer.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/TagAnalyzer.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/TagAnalyzerFactory.java
- src/main/java/io/luchta/forma4j/reader/xml/relation/taganalyzer/VForTagAnalyzer.java
- src/test/java/io/luchta/forma4j/reader/FormaReaderTest.java
- src/test/java/io/luchta/forma4j/reader/hfor/HForTest.java
hforの読み取り結果のフォーマットが想定外のものなっているため修正。
> hforの読み取り結果フォーマット修正

- src/main/java/io/luchta/forma4j/reader/excel/property/handler/BreakConditionHandler.java
- src/test/java/io/luchta/forma4j/reader/vfor/VForTest.java
- src/test/resources/reader/vfor/vfor_all_blank_with_hfor.xml
v-forやh-forを使用して行を読み込むとき、行の最後のセルの値がブランクだとブレイクしてしまう不具合を修正。
> break=all_blankの不具合修正
